### ISSUE TITLE
remove unneeded dependencies

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishobs#19]
pgdata - unnecessary
psqlcsv - use `/copy` OR, even better - create a table to hold the summary and write the results with a timestamp each time job is run

**Comment by smnorris** [comment]
keeping psql2csv for now, it is handy

**Comment by NewGraphEnvironment** [comment]
unfortunately `psql2csv` causes a build failure and workflow kick-out on linux machines since it is a mac specific software...

 Perhaps a switch  to  `make .linux` or something to turn it off?

**Comment by smnorris** [comment]
It is not Mac specific. See "Manual" installation method in psql2csv readme

**Comment by NewGraphEnvironment** [comment]
nice!

`$ curl https://raw.githubusercontent.com/fphilipe/psql2csv/master/psql2csv > /usr/local/bin/psql2csv && chmod +x /usr/local/bin/psql2csv`
